### ISSUE TITLE
GetFunctionPointerForDelegate is UNSAFE and may be GCed

### ISSUE THREAD

**Issue by LoyieKing** [FICTURE7/unicorn-net#8]
HookContainers call `AddInternal` to bind .NET delegate and unicorn hook callbacks.
but these AddInternals , just simply `new` a delegate and use `Marshal.GetFunctionPointerForDelegate` to bind native pointers.
But there is a problem that .NET RT may **GC**  these delegate and cause Execption like this
![image](https://user-images.githubusercontent.com/13981123/62002759-e2efd280-b13d-11e9-9ee6-f47c67dd5b11.png)

> "**CallbackOnCollectedDelegate**": "A callback was made to a garbage collection delegate of type "Unicorn.Net!Unicorn.Internal.uc_cb_hookcode::Invoke". This could cause application crashes, corruption, and data loss. When passing a delegate to unmanaged code The managed application must keep these delegates active until they are sure they will not be called again."

I suggest create a List&lt;object&gt; field to save all delegates in order to avoid GC

**Comment by FICTURE7** [comment]
Thanks for reporting this, it should be fixed now.
